# 应用名称
spring:
  application:
    name: order-service
  cloud:
    config:
      override-none: true

# 应用服务 WEB 访问端口
#server:
  #port: 8201
  
eureka:
  client:
    service-url:
      #表示 eureka 服务器的部署位置, 需要云服务器提供
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka

feign:
  hystrix:
    enabled: true

#hystrix超时设置，为了测试 hystrix 降级，我们把 hystrix等待超时设置得非常小（500毫秒）
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

rabbitmq:
    host: 192.168.92.133
    port: 5672
    username: admin
    password: admin


---
spring:
  profiles: orderservice1
  
server:
  port: 8201
  
---
spring:
  profiles: orderservice2
 
server:
  port: 8202